# Generated by Django 5.0.6 on 2024-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('User', 'User'), ('shop owner', 'Shopowner')], default='User', max_length=20),
        ),
    ]
